server:
  port: 3344

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuan-sha/microservicecloud-config.git
  application:
    name: microservicecloud-config
